### ISSUE TITLE
Publish MySQL 8.0.27

### ISSUE THREAD

**Issue by paskal** [jamielsharief/docker-mysql#2]
Hi there, thanks for (almost) drop-in replacement for MySQL image for arm64! Would you be so kind as to rebuild and publish the image so it would receive 8.0.27 version?

Otherwise, I see the following error after migration:

```
[ERROR] [MY-013171] [InnoDB] Cannot boot server version 80022 on data directory built by version 80027. Downgrade is not supported
```

To fix I had to do the following steps:

```shell
git clone https://github.com/jamielsharief/docker-mysql.git
cd docker-mysql
docker build -t jamielsharief/mysql:latest .
```

**Comment by jamielsharief** [comment]
Thanks for using it , I will fix this shortly.

**Comment by jamielsharief** [comment]
I have fixed this by setting up the CI to run this daily, so from now on this should always be pretty much up to date.

I just ran `docker pull jamielsharief/mysql` and MySQL is on 8.0.27.

Thanks.
